### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AslanAmca** [ChimPansky/42_exam05#1]
Hello. I am opening this issue to ask a question about Exam 05. Do created or removed objects need to be deleted?

Some examples on GitHub take into account the memory leak situation, others don't use delete for any object. 

If you have given the exam, you know the answer, I would appreciate a response.

**Comment by ChimPansky** [comment]
Hi!
During the exam I didn't delete the spells/targets (therefore having memory leaks) and it passed. 
That being said, the nicer and more correct way would be, to delete them in the forgetSpell and forgetTargetType functions as well as in the Destructor of Warlock/Spellbook/TargetGenerator...
